### ISSUE TITLE
GIFT PPA provides 20180818-1ppa1~bionic instead of 20180930-1ppa1~bionic

### ISSUE THREAD

**Issue by 3Fingers** [log2timeline/plaso#2185]
**Description of problem:**

Fresh install on Ubuntu 18.04 experiencing errors when first running log2timeline

**Command line and arguments:**

log2timeline --info

**Source data:**

Installed per directions on site

**Plaso version:**

~20180930~ 
20180818

**Operating system Plaso is running on:**

Ubuntu 18.04

**Installation method:**

Followed steps detailed at https://github.com/log2timeline/plaso/wiki/Ubuntu-Packaged-Release

**Debug output/tracebacks:**
log2timeline.py --info
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 12, in <module>
    from plaso.cli import log2timeline_tool
  File "/usr/lib/python2.7/dist-packages/plaso/cli/log2timeline_tool.py", line 19, in <module>
    from plaso.cli import extraction_tool
  File "/usr/lib/python2.7/dist-packages/plaso/cli/extraction_tool.py", line 12, in <module>
    from plaso import parsers  # pylint: disable=unused-import
  File "/usr/lib/python2.7/dist-packages/plaso/parsers/__init__.py", line 13, in <module>
    from plaso.parsers import custom_destinations
  File "/usr/lib/python2.7/dist-packages/plaso/parsers/custom_destinations.py", line 20, in <module>
    class CustomDestinationsParser(interface.FileObjectParser):
  File "/usr/lib/python2.7/dist-packages/plaso/parsers/custom_destinations.py", line 39, in CustomDestinationsParser
    construct.ULInt32('unknown1'),
AttributeError: 'module' object has no attribute 'ULInt32'

**Comment by joachimmetz** [comment]
The error you are seeing is related to incompatibility of the API of newer versions of construct. However the 20180930 version of plaso no longer uses construct: https://github.com/log2timeline/plaso/blob/20180930/plaso/parsers/custom_destinations.py

It looks like the PPA does not provide the latest version of plaso for bionic
https://launchpad.net/~gift/+archive/ubuntu/stable/+packages?field.name_filter=plaso&field.status_filter=published&field.series_filter=

**Comment by joachimmetz** [comment]
Related https://github.com/log2timeline/l2tdevtools/issues/347 18.04 support is still WIP.

**Comment by joachimmetz** [comment]
Initial work on l2tbinaries Ubuntu 16.04 and 18.04 tests: https://ci.appveyor.com/project/Log2timeline/l2tbinaries/builds/20316806

**Comment by joachimmetz** [comment]
efilter was missing for bionic as well

**Comment by joachimmetz** [comment]
tested new version on bionic live CD, was able to successfully run log2timeline.py. Closing issue.
