### ISSUE TITLE
TypeError after installation

### ISSUE THREAD

**Issue by zappeee** [log2timeline/plaso#987]
**Plaso version:**

Not sure

**Operating system Plaso is running on:**

Ubuntu 14.04

**Installation method:**

Via SIFT

**Description of problem:**

Just trying to run anything with log2timeline.py gives me errors

sansforensics@siftworkstation:~$ log2timeline.py -V
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 22, in <module>
    from plaso.cli import extraction_tool
  File "/usr/lib/python2.7/dist-packages/plaso/cli/extraction_tool.py", line 7, in <module>
    from plaso.engine import engine
  File "/usr/lib/python2.7/dist-packages/plaso/engine/engine.py", line 14, in <module>
    from plaso.preprocessors import interface as preprocess_interface
  File "/usr/lib/python2.7/dist-packages/plaso/preprocessors/__init__.py", line 5, in <module>
    from plaso.preprocessors import macosx
  File "/usr/lib/python2.7/dist-packages/plaso/preprocessors/macosx.py", line 10, in <module>
    from plaso.parsers.plist_plugins import interface as plist_interface
  File "/usr/lib/python2.7/dist-packages/plaso/parsers/__init__.py", line 10, in <module>
    from plaso.parsers import cups_ipp
  File "/usr/lib/python2.7/dist-packages/plaso/parsers/cups_ipp.py", line 108, in <module>
    class CupsIppParser(interface.FileObjectParser):
  File "/usr/lib/python2.7/dist-packages/plaso/parsers/cups_ipp.py", line 165, in CupsIppParser
    length_field=construct.UBInt8(u'length'))
TypeError: __init__() got an unexpected keyword argument 'length_field'

**Debug output/tracebacks:**

-

**Source data:**

-

**Comment by joachimmetz** [comment]
Your construct is too new, switch back to 2.5.2 or 2.53

**Comment by joachimmetz** [comment]
Related to: https://github.com/log2timeline/plaso/issues/981

**Comment by zappeee** [comment]
Oh, SIFT automatically installs 2.6.2.

When will log2timeline support newer construct?

**Comment by zappeee** [comment]
Btw, any idea how to install 2.5.*?
Python package, https://pypi.python.org/pypi/construct, has been upgrade to 2.6.2

**Comment by joachimmetz** [comment]
per construct developer 2.6.x is beta (or work in progress) and 2.7.x is the next stable
See: https://pypi.python.org/pypi/construct

we'll likely experiment with 2.6.x in the next development release, ask sift the revert back to 2.5.x since the new version will break more applications that use construct 2.5.x

**Comment by joachimmetz** [comment]
> Btw, any idea how to install 2.5.*?

just install it from GIFT (pun intended) https://launchpad.net/~gift/+archive/ubuntu/stable

**Comment by zappeee** [comment]
Nevermind, solved in https://github.com/construct/construct/issues/72
