### ISSUE TITLE
ImportError: cannot import name protobuf_serializer

### ISSUE THREAD

**Issue by jpoling-dswrx** [log2timeline/plaso#862]
**Plaso version:**

Likely some version >= 1.4.1_20160131? Can't tell because log2timeline.py no longer runs to retrieve the version number. 

**Operating system Plaso is running on:**

Fedora 23

**Installation method:**

CERT Forensics Repo

**Description of problem:**

With Plaso version 1.4.1_20160131 successfully running on a Fedora Core 23 system instrumented with the CERT Forensics Repo, issugin a "dnf update" breaks log2timeline.py yielding "ImportError: cannot import name protobuf_serializer"

**Debug output/tracebacks:**

> # log2timeline.py -d -V
Traceback (most recent call last):
  File "/bin/log2timeline.py", line 25, in <module>
    from plaso.frontend import log2timeline
  File "/usr/lib/python2.7/site-packages/plaso/frontend/log2timeline.py", line 15, in <module>
    from plaso import output  # pylint: disable=unused-import
  File "/usr/lib/python2.7/site-packages/plaso/output/__init__.py", line 12, in <module>
    from plaso.output import pstorage
  File "/usr/lib/python2.7/site-packages/plaso/output/pstorage.py", line 9, in <module>
    from plaso.storage import zip_file
  File "/usr/lib/python2.7/site-packages/plaso/storage/zip_file.py", line 101, in <module>
    from plaso.serializer import protobuf_serializer
  File "/usr/lib/python2.7/site-packages/plaso/serializer/protobuf_serializer.py", line 6, in <module>
    from dfvfs.serializer import protobuf_serializer as dfvfs_protobuf_serializer
ImportError: cannot import name protobuf_serializer

**Source data:**

Unknown. I presume something that has been updated with the latest dnf update, either plaso itself or some other dependency.

**Comment by joachimmetz** [comment]
Per: https://github.com/log2timeline/plaso/issues/803

Protobuf support has been deprecated in dfvfs and in plaso (after 1.4.0). 
This version of dfvfs should still contain protobuf support https://github.com/log2timeline/dfvfs/releases/tag/20160108

**Comment by joachimmetz** [comment]
Also 1.4.1_20160131 is a dev version why is CERT Forensics Repo distributing a dev version?

**Comment by jpoling-dswrx** [comment]
Excellent question. I have no idea why they are doing that. However, a dnf update now yields an unusable log2timeline. 

So, what's the quickest way to get back on track here?

**Comment by joachimmetz** [comment]
with dev or stable?

For dev plaso just `git clone` HEAD and run from it e.g. `PYTHONPATH=~/plaso plaso/tools/log2timeline.py`

We just announced feature freeze so we are working on getting 1.5 ready for a release candidate.

**Comment by joachimmetz** [comment]
dev has some new dependencies though, but no longer requires protobuf.

**Comment by jpoling-dswrx** [comment]
Only interested in getting back up and running with latest stable release at this point.

**Comment by joachimmetz** [comment]
depends on CERT Forensics Repo

but you can always boot a live Ubuntu 14.04 and pull in from the GIFT stable PPA

**Comment by jpoling-dswrx** [comment]
Looks like plaso-1.4-3.fc23.x86_64 is the latest package being offered through CERT Forensics Repo that apparently is broken. 

https://forensics.cert.org/fedora/cert/23/x86_64/repoview/plaso.html

**Comment by joachimmetz** [comment]
You'll have to reach out to "CERT Forensics Repo" we did not package it and cannot change anything about it. Closing this issue since there are other methods to install plaso.

**Comment by jpoling-dswrx** [comment]
What is the latest stable release version that CERT should have? As of right now, version query yields 1.4.1_20160131.

**Comment by joachimmetz** [comment]
> What is the latest stable release version that CERT should have? 

Note that we use "packaged" version not "stable". See: https://github.com/log2timeline/plaso/wiki/Releases-and-roadmap

Plaso is beta not stable, the development status is indicate here https://github.com/log2timeline/plaso/blob/master/setup.py#L98

"1.4.0" is the last packaged release

The version format "1.4.1_20160131" is only used for developer releases

**Comment by jpoling-dswrx** [comment]
Great, thanks.
