### ISSUE TITLE
Handle de-serialization of SemanticTime objects

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#3268]
Issue introduced by https://github.com/log2timeline/plaso/commit/98e302ba931be9013463d554a4ee795770a03c9d

```
Traceback (most recent call last):
  File "plaso/storage/interface.py", line 643, in _DeserializeAttributeContainer
    attribute_container = self._serializer.ReadSerialized(serialized_string)
  File "plaso/serializer/json_serializer.py", line 556, in ReadSerialized
    return cls.ReadSerializedDict(json_dict)
  File "plaso/serializer/json_serializer.py", line 575, in ReadSerializedDict
    json_object = cls._ConvertDictToObject(json_dict)
  File "plaso/serializer/json_serializer.py", line 276, in _ConvertDictToObject
    attribute_value = cls._ConvertDictToObject(attribute_value)
  File "plaso/serializer/json_serializer.py", line 231, in _ConvertDictToObject
    return cls._ConvertDictToDateTimeValues(json_dict)
  File "plaso/serializer/json_serializer.py", line 380, in _ConvertDictToDateTimeValues
    date_time = dfdatetime_factory.Factory.NewDateTimeValues(
  File "/usr/lib/python3.8/site-packages/dfdatetime/factory.py", line 48, in NewDateTimeValues
    return date_time_values_type(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'string'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib64/python3.8/cProfile.py", line 196, in <module>
    main()
  File "/usr/lib64/python3.8/cProfile.py", line 189, in main
    runctx(code, globs, None, options.outfile, options.sort)
  File "/usr/lib64/python3.8/cProfile.py", line 19, in runctx
    return _pyprofile._Utils(Profile).runctx(statement, globals, locals,
  File "/usr/lib64/python3.8/profile.py", line 62, in runctx
    prof.runctx(statement, globals, locals)
  File "/usr/lib64/python3.8/cProfile.py", line 100, in runctx
    exec(cmd, globals, locals)
  File "tools/psort.py", line 99, in <module>
    if not Main():
  File "tools/psort.py", line 76, in Main
    tool.ProcessStorage()
  File "plaso/cli/psort_tool.py", line 593, in ProcessStorage
    analysis_engine.ExportEvents(
  File "plaso/multi_processing/psort.py", line 1042, in ExportEvents
    self._ExportEvents(
  File "plaso/multi_processing/psort.py", line 524, in _ExportEvents
    for event in storage_reader.GetSortedEvents(time_range=time_slice_range):
  File "plaso/storage/sqlite/sqlite_file.py", line 1020, in GetSortedEvents
    for event in event_generator:
  File "plaso/storage/sqlite/sqlite_file.py", line 414, in _GetAttributeContainers
    attribute_container = self._DeserializeAttributeContainer(
  File "plaso/storage/interface.py", line 650, in _DeserializeAttributeContainer
    raise IOError('Unable to read serialized data: {0!s}'.format(exception))
OSError: Unable to read serialized data: __init__() got an unexpected keyword argument 'string'
```
