### ISSUE TITLE
Python Virtualenv Install Fails

### ISSUE THREAD

**Issue by cshanahan** [log2timeline/plaso#1015]
**Plaso version:**
1.5.0 Release

**Operating system Plaso is running on:**
Ubuntu 16.04.1 64-bit

**Installation method:**
Installed Plaso from source using python virtualenv, described here: https://github.com/log2timeline/plaso/wiki/running-plaso-in-virtualenv

**Description of problem:**
I created a new virtual machine running Ubuntu 16.04.1 to test the installation routine for Plaso 1.5 using python virtualenv. I followed the usual directions and installed all dependencies without error, including libyaml-dev. Then I installed Plaso from source. Also no errors. Running any subsequent Plaso command (e.g., log2timeline.py --help) generates the following error:

`
Traceback (most recent call last):
  File "/home/uvm/bin/plasoenv/bin/log2timeline.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==1.5.0', 'log2timeline.py')
  File "/home/uvm/bin/plasoenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/uvm/bin/plasoenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/home/uvm/bin/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 21, in <module>
    from plaso.cli import extraction_tool
  File "/home/uvm/bin/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/plaso/cli/extraction_tool.py", line 8, in <module>
    from plaso.cli import storage_media_tool
  File "/home/uvm/bin/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/plaso/cli/storage_media_tool.py", line 9, in <module>
    from dfvfs.analyzer import analyzer as dfvfs_analyzer
  File "/home/uvm/bin/plasoenv/local/lib/python2.7/site-packages/dfvfs/analyzer/__init__.py", line 4, in <module>
    from dfvfs.analyzer import bde_analyzer_helper
  File "/home/uvm/bin/plasoenv/local/lib/python2.7/site-packages/dfvfs/analyzer/bde_analyzer_helper.py", line 4, in <module>
    from dfvfs.analyzer import analyzer
  File "/home/uvm/bin/plasoenv/local/lib/python2.7/site-packages/dfvfs/analyzer/analyzer.py", line 9, in <module>
    from dfvfs.resolver import resolver
  File "/home/uvm/bin/plasoenv/local/lib/python2.7/site-packages/dfvfs/resolver/__init__.py", line 10, in <module>
    from dfvfs.resolver import cpio_resolver_helper
  File "/home/uvm/bin/plasoenv/local/lib/python2.7/site-packages/dfvfs/resolver/cpio_resolver_helper.py", line 6, in <module>
    import dfvfs.vfs.cpio_file_system
  File "/home/uvm/bin/plasoenv/local/lib/python2.7/site-packages/dfvfs/vfs/cpio_file_system.py", line 7, in <module>
    from dfvfs.lib import cpio
  File "/home/uvm/bin/plasoenv/local/lib/python2.7/site-packages/dfvfs/lib/cpio.py", line 38, in <module>
    class CPIOArchiveFile(object):
  File "/home/uvm/bin/plasoenv/local/lib/python2.7/site-packages/dfvfs/lib/cpio.py", line 52, in CPIOArchiveFile
    construct.UBInt16(u'signature'),
AttributeError: 'module' object has no attribute 'UBInt16'
`

I also tried the same process on another system running openSUSE 42.1. No errors during installation yet I got the same error when running any Plaso command (log2timeline, psort, pinfo, etc.). I also made sure pip cache was clear before the installation.

I should note, I run other applications using python virtualenv, including Rekall, without any problems.

If you'd like me to try anything else, let me know. I'd be happy to help.

--
Chris

**Comment by Onager** [comment]
This looks like an wrong version of construct - can you check the version
you're using?

**Comment by Onager** [comment]
It looks like a construct 2.8.5 was just released, which removed this class, and drastically changed the construct API.

**Comment by Onager** [comment]
This looks to be an issue with the requirements file - we  specify `construct >= 2.5.2`, but don't work with 2.6 and above.

**Comment by cshanahan** [comment]
I checked both installations I have and construct 2.8.5 was installed. I edited the requirements file to include a min and max version, like you did in your fork (https://github.com/Onager/plaso/commit/2c30f7f54345ef47524585e96b5744f2c7496181). Construct 2.8.3 gets installed; however, now there is a new error:

`
Traceback (most recent call last):
  File "/home/uvm/bin/plasoenv/bin/psort.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==1.5.0', 'psort.py')
  File "/home/uvm/bin/plasoenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/uvm/bin/plasoenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/home/uvm/bin/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/EGG-INFO/scripts/psort.py", line 27, in <module>
    from plaso import filters  # pylint: disable=unused-import
  File "/home/uvm/bin/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/plaso/filters/__init__.py", line 4, in <module>
    from plaso.filters import dynamic_filter
  File "/home/uvm/bin/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/plaso/filters/dynamic_filter.py", line 4, in <module>
    from plaso.filters import event_filter
  File "/home/uvm/bin/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/plaso/filters/event_filter.py", line 4, in <module>
    from plaso.filters import interface
  File "/home/uvm/bin/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/plaso/filters/interface.py", line 7, in <module>
    from plaso.lib import pfilter
  File "/home/uvm/bin/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/plaso/lib/pfilter.py", line 16, in <module>
    from plaso.parsers import presets
  File "/home/uvm/bin/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/plaso/parsers/__init__.py", line 8, in <module>
    from plaso.parsers import chrome_cache
  File "/home/uvm/bin/plasoenv/lib/python2.7/site-packages/plaso-1.5.0-py2.7.egg/plaso/parsers/chrome_cache.py", line 8, in <module>
    from dfvfs.resolver import resolver as path_spec_resolver
  File "/home/uvm/bin/plasoenv/local/lib/python2.7/site-packages/dfvfs/resolver/__init__.py", line 13, in <module>
    from dfvfs.resolver import encrypted_stream_resolver_helper
  File "/home/uvm/bin/plasoenv/local/lib/python2.7/site-packages/dfvfs/resolver/encrypted_stream_resolver_helper.py", line 5, in <module>
    import dfvfs.file_io.encrypted_stream_io
  File "/home/uvm/bin/plasoenv/local/lib/python2.7/site-packages/dfvfs/file_io/encrypted_stream_io.py", line 6, in <module>
    from dfvfs.encryption import manager as encryption_manager
  File "/home/uvm/bin/plasoenv/local/lib/python2.7/site-packages/dfvfs/encryption/__init__.py", line 4, in <module>
    from dfvfs.encryption import aes_decrypter
  File "/home/uvm/bin/plasoenv/local/lib/python2.7/site-packages/dfvfs/encryption/aes_decrypter.py", line 4, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher
`

Which package provided crypto.cipher?
Thank you for looking at this so quickly Daniel.

--
Chris

**Comment by Onager** [comment]
2.8.3 is still too new, you'll need a 2.5.x construct version.

**Comment by cshanahan** [comment]
Weird... I didn't notice the version falls outside what I specified. Any idea why am I getting construct 2.8.3 if the requirements file says "construct >=2.5.2,<=2.6.0"
Syntax looks correct:
https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format

Would it be better to just specify the exact version you know works as expected for Plaso 1.5?


--
Chris

**Comment by cshanahan** [comment]
This issue is resolved for me and Plaso seems to be working as expected now. To summarize, I updated the requirement file to specify construct 2.5.3. I also installed pycrypto in the virtualenv (see #1024).

Thanks for looking at this so quickly.

--
Chris

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/310400043/diff/1/plaso/dependencies.py

**Comment by joachimmetz** [comment]
> 2.8.3 is still too new, you'll need a 2.5.x construct version.

To be verbose you'll need construct 2.5.2 or 2.5.3

**Comment by joachimmetz** [comment]
> Would it be better to just specify the exact version you know works as expected for Plaso 1.5?

"better" is a value judgement.

pinning to specific versions is not best practice if a package comes with fixes you cannot update.

However if the API changes things will break. It would be nice if most package manager actually would decouple package version from API version.
